# Generated by Django 3.1.1 on 2020-09-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('web', '0001_initial')]

    operations = [migrations.DeleteModel(name='Paste')]
