# Generated by Django 3.1.1 on 2020-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
