# Generated by Django 3.1.1 on 2020-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0002_paste_expiry')]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        )
    ]
