# Generated by Django 3.1.1 on 2020-09-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0003_paste_hits')]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
