# Generated by Django 3.1.1 on 2020-09-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    def resave(apps, schema_editor):
        Paste = apps.get_model('core', 'Paste')
        for p in Paste.objects.all():
            # p.save() does not appear to call the custom save method on the
            # Paste model :/ So just reproduce the logic here.
            p.size = sum([
                len(p.title.encode('utf-8')),
                len(p.body.encode('utf-8')),
            ])
            p.save()

    def do_nothing(apps, schema_editor):
        pass

    dependencies = [
        ('core', '0005_expirylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(resave, do_nothing),
    ]
