# Generated by Django 3.1.1 on 2020-09-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200908_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paste',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='paste',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
