# Generated by Django 3.1.1 on 2020-09-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0009_auto_20200910_0350')]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='freeze_hits',
            field=models.BooleanField(blank=True, default=False),
        )
    ]
