# Generated by Django 3.1.1 on 2020-11-05 02:03

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paste_freeze_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
    ]
