# Generated by Django 3.1.12 on 2021-08-13 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201105_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expirylog',
            old_name='count',
            new_name='paste_count',
        ),
        migrations.AddField(
            model_name='expirylog',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expirylog',
            name='user_cutoff',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
