# Generated by Django 3.1.13 on 2022-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210813_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
